### ISSUE TITLE
request to add CC and EC class in seat options

### ISSUE THREAD

**Issue by 520rahul** [dpak-maurya/irctc-tatkal-ticket-booking#12]
Dear Sir, plz add CC and EC class in seat options as rajdhani and double decker have these type of seats. And can u plz guide what time we should run the extension for booking tatkal ticket to get the maximum possibility of ticket booking whether it is 9.59.53 or it may be later or earlier. One more request the extension books the normal ticket even it is showing in waiting even if we selected book only when confirm option in extension, therefore kindly update it so that it can book only confirm ticket not waiting list

**Comment by 520rahul** [comment]
@dpak-maurya sir please update extension itd a humble requst

**Comment by dpak-maurya** [comment]
Hi Rahul, thanks for sharing your concern. Give me some time, Currently I
am facing some issues with my laptop. So I don't have access to the code
repository. Once I get back my working laptop, I will update the seat
options.

**Comment by dpak-maurya** [comment]
Earlier the timer was 9.59.45 and someone reported that it's not clicking
the book now button, so I updated it to 9.59.53 after testing. So it was
working for me. You can try changing time based on your preference i.e. 5
seconds up or down

**Comment by 520rahul** [comment]
@dpak-maurya i hope u wil update repo for my another issue as highlighted by me on my issue that even if we select "book only if confirm seat is alloted" still the repo books waiting list tickets also. I tried it in general booking plz look into this also.

**Comment by dpak-maurya** [comment]
There is option for if only confirm birth allotted this option is only available if train has available seats before booking you can check it out once. If there is already waiting lists then this option will not work. you can check in the popup window while filling captcha whether to proceed or not i.e. Current Seat Status
<img width="436" alt="image" src="https://github.com/user-attachments/assets/933f9cea-a958-4070-8fa1-9d4b1125beb1">
