### ISSUE TITLE
Issue on auto booking it opens multiple irctc tabs 

### ISSUE THREAD

**Issue by brupadhyay** [dpak-maurya/irctc-tatkal-ticket-booking#13]
Basically what happens is, it tries to login just 2mins before the start time, so at the time of login my extension opens multiple tabs approx 10 tabs so it starts taking more bandwidth and I was not able to book a ticket today

Manual TroubleShoot is there - we can close the tabs and allow only one tab to be opened, but still it should not open many tabs

**Comment by dpak-maurya** [comment]
Hi Bhavesh thanks for highlighting this issue. Once I get time to look, I
will fix the issue.

**Comment by dpak-maurya** [comment]
@brupadhyay  i have fixed the code. please check if the issue still persists, let me know.
