### ISSUE TITLE
"Book Only If Confirm Berths are Alloted" Feature Not Working for Waitlisted Tickets

### ISSUE THREAD

**Issue by Nilanjan-B** [dpak-maurya/irctc-tatkal-ticket-booking#17]
![image](https://github.com/user-attachments/assets/c5158450-f9f3-4785-a16d-8e18c3810db5)
![image](https://github.com/user-attachments/assets/e826a37c-6e98-405e-8108-e6432eb7034b)

This **"Book Only If Confirm Berths are Alloted"**  feature of The Extension is not working for trains which already gone for waitlist as there don't have the feature in the irctc website by default for waitlist tickets besides the **"Consider for Auto Upgradation"** Tick Box. That's why this feature is not working. Solve this issue for Waitlist Ticket to stop booking if the ticket already gone for waitlist. See the image, you can see the bug. Please Solve it @dpak-maurya

**Comment by dpak-maurya** [comment]
@Nilanjan-B yes i will check this issue. Actually another user have also shared similar feedback. i will see that what can be improve.
