### ISSUE TITLE
Give Form Field Box for Auto-Login Time before Tatkal Start Timer

### ISSUE THREAD

**Issue by Nilanjan-B** [dpak-maurya/irctc-tatkal-ticket-booking#19]
![image](https://github.com/user-attachments/assets/335f7114-a9f3-4922-a1a0-5a6153bb2819)
![image](https://github.com/user-attachments/assets/20ee2e82-ea70-4865-a88b-7a77bd6ed6d6)

@dpak-maurya sir, **Please Give a Form Field Box Below the Tatkal Timer Details and Refresh Timer Fields, So anyone can modify the timer according to their need, not a fix 2 Minutes Before Tatkal Timer Login**

The reason I'm asking for this because I found a fault in irctc website that sometimes after entering valid captcha and auto credentials, the irctc login page show some error and ask to login again. It consumes a lot of time to re-loging specially if one using multiple chrome profiles and multiple irctc id to book tatkal ticket.

This extension is awesome. This is the best IRCTC Tatkal Booking Repository in Github. I recommend you to publish this extension in Chrome Web Store also. Thank you.

**Comment by dpak-maurya** [comment]
thanks @Nilanjan-B for giving this critical feedback. i will definitley include this in next feature update.
