### ISSUE TITLE
"Sorry!!! Please Try Again!!!" page appears when trying to login, with extension loaded in chrome

### ISSUE THREAD

**Issue by jibin23** [dpak-maurya/irctc-tatkal-ticket-booking#25]
**Update 2:** 
1. Manual login is working in incognito, while the extension is enabled, but Auto Booking is off.
2. However, when Auto Booking is turned on, the "Sorry!!! Please Try Again!!!" comes again.
![image](https://github.com/user-attachments/assets/5bf8932a-a2f7-4f3b-91db-7933a277d529)

This is the error in the extension:
![image](https://github.com/user-attachments/assets/c6859880-d4ce-4f31-ac3b-dc4efbbae63f)

**Update 1:** 
This problem goes away when I open the website on icognito, even if the chrome extension is enabled in incognito mode. Currently the website is in maintenance, I will try the whole flow once.

**Original:**
I just loaded the unpacked extension and filled no form. Then I just go to IRCTC in a new tab and try to login. I am redirected to the following page: https://www.irctc.co.in/nget/error, with the attached screenshot.
<img width="1098" alt="TATKAL_EXT" src="https://github.com/user-attachments/assets/8b870307-2b9c-4021-866b-791974ef3f01">
This problem goes away, when I open it incognito, where the extention is not enabled. What can be causing this?

**Comment by dpak-maurya** [comment]
Can you help me replicate the issue? Like what's the exact steps you have
taken

**Comment by dpak-maurya** [comment]
Hi @jibin23 , i checked this error. most of time this error comes when your internet comes from public wifi/ router or you have tried logining multiple times within few minutes. if you use mobile hotspot, then this error goes away. let me know if this helps.

**Comment by rockydares** [comment]
I have this same issue. When booking tatakal and after putting the captcha and clicking 'Enter' button gives this error. Even when not using extension gives this error at the tatkal booking time. Only if I manually click on the Login button, then this problem does not occur.
